# name of the profile, we will auto prefix with `docker-`
# so the final profile name will be `docker-csplogger-apparmor`
Name = "csplogger-apparmor"

[Filesystem]
# read only paths for the container
ReadOnlyPaths = [
	"/bin/**",
	"/boot/**",
	"/dev/**",
	"/etc/**",
	"/lib/**",
	"/lib64/**",
	"/media/**",
	"/mnt/**",
	"/opt/**",
	"/proc/**",
	"/root/**",
	"/sbin/**",
	"/srv/**",
	"/tmp/**",
	"/sys/**",
	"/usr/**",
]

# paths where you want to log on write
LogOnWritePaths = [
	"/**"
]

# paths where you can write
WritablePaths = [
	"/home/csplogger-agent/csplogger/databases"
]

# allowed executable files for the container
AllowExec = [
	"/bin/id",
	"/bin/sh"
]


# denied executable files
DenyExec = [
	"/sbin/*",
	"/bin/arch",
	"/bin/ash",
	"/bin/base64",
	"/bin/bbconfig",
	"/bin/busybox",
	"/bin/cat",
	"/bin/chgrp",
	"/bin/chmod",
	"/bin/chown",
	"/bin/conspy",
	"/bin/cp",
	"/bin/date",
	"/bin/dd",
	"/bin/df",
	"/bin/dmesg",
	"/bin/dnsdomainname",
	"/bin/dumpkmap",
	"/bin/echo",
	"/bin/ed",
	"/bin/egrep",
	"/bin/false",
	"/bin/fatattr",
	"/bin/fdflush",
	"/bin/fgrep",
	"/bin/fsync",
	"/bin/getopt",
	"/bin/grep",
	"/bin/gunzip",
	"/bin/gzip",
	"/bin/hostname",
	"/bin/ionice",
	"/bin/iostat",
	"/bin/ipcalc",
	"/bin/kbd_mode",
	"/bin/kill",
	"/bin/link",
	"/bin/linux32",
	"/bin/linux64",
	"/bin/ln",
	"/bin/login",
	"/bin/ls",
	"/bin/lzop",
	"/bin/makemime",
	"/bin/mkdir",
	"/bin/mknod",
	"/bin/mktemp",
	"/bin/more",
	"/bin/mount",
	"/bin/mountpoint",
	"/bin/mpstat",
	"/bin/mv",
	"/bin/netstat",
	"/bin/nice",
	"/bin/pidof",
	"/bin/ping",
	"/bin/ping6",
	"/bin/pipe_progress",
	"/bin/printenv",
	"/bin/ps",
	"/bin/pwd",
	"/bin/reformime",
	"/bin/rev",
	"/bin/rm",
	"/bin/rmdir",
	"/bin/run-parts",
	"/bin/sed",
	"/bin/setpriv",
	"/bin/setserial",
	"/bin/sleep",
	"/bin/stat",
	"/bin/stty",
	"/bin/su",
	"/bin/sync",
	"/bin/tar",
	"/bin/touch",
	"/bin/true",
	"/bin/umount",
	"/bin/uname",
	"/bin/usleep",
	"/bin/watch",
	"/bin/zcat",
	"/usr/bin/*",
	"/usr/sbin/*"
]

# allowed capabilities
[Capabilities]
Allow = [
]

[Network]
# if you don't need to ping in a container, you can probably
# set Raw to false and deny network raw
Raw = false
Packet = false
Protocols = [
	"tcp"
]


